// Code generated by goctl. DO NOT EDIT.
package types

type CancelOrderReq struct {
	Id     int64  `path:"id"`
	UserId string `json:"userId,optional"`
}

type CancelOrderResp struct {
	Default
}

type Default struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type HistoryOrders struct {
	Total   int64              `json:"total"`
	Records []*OrderWithDetail `json:"records"`
}

type HistoryOrdersReq struct {
	UserId   string `form:"userId,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
	Status   int64  `form:"status,optional"`
}

type HistoryOrdersResp struct {
	Default
	Orders struct {
		Total   int64              `json:"total"`
		Records []*OrderWithDetail `json:"records"`
	} `json:"data"`
}

type Order struct {
	Id                    int64  `json:"id"`
	Number                string `json:"number"`
	Status                int64  `json:"status"`
	UserId                string `json:"userId"`
	AddressBookId         int64  `json:"addressBookId"`
	OrderTime             string `json:"orderTime"`
	CheckoutTime          string `json:"checkoutTime"`
	PayMethod             int64  `json:"payMethod"`
	PayStatus             int64  `json:"payStatus"`
	Amount                int64  `json:"amount"`
	Remark                string `json:"remark"`
	UserName              string `json:"userName"`
	Phone                 string `json:"phone"`
	Address               string `json:"address"`
	Consignee             string `json:"consignee"`
	CancelReason          string `json:"cancelReason"`
	RejectionReason       string `json:"rejectionReason"`
	CancelTime            string `json:"cancelTime"`
	EstimatedDeliveryTime string `json:"estimatedDeliveryTime"`
	DeliveryStatus        int64  `json:"deliveryStatus"`
	DeliveryTime          string `json:"deliveryTime"`
	PackAmount            int64  `json:"packAmount"`
	TablewareNumber       int64  `json:"tablewareNumber"`
	TablewareStatus       int64  `json:"tablewareStatus"`
	OrderDishes           string `json:"orderDishes"`
}

type OrderDetail struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`
	OrderId    int64  `json:"orderId"`
	DishId     int64  `json:"dishId"`
	SetmealId  int64  `json:"setmealId"`
	DishFlavor string `json:"dishFlavor"`
	Number     int64  `json:"number"`
	Amount     int64  `json:"amount"`
	Pic        string `json:"pic"`
}

type OrderDetailReq struct {
	Id     int64  `path:"id"`
	UserId string `json:"userId,optional"`
}

type OrderDetailResp struct {
	Default
	Orders struct {
		Order
		OrderDetailList []*OrderDetail `json:"orderDetailList"`
	} `json:"data"`
}

type OrderWithDetail struct {
	Order
	OrderDetailList []*OrderDetail `json:"orderDetailList"`
}

type Payment struct {
	NonceStr   string `json:"nonceStr"`
	PaySign    string `json:"paySign"`
	TimeStamp  string `json:"timeStamp"`
	SignType   string `json:"signType"`
	PackageStr string `json:"packageStr"`
}

type PaymentReq struct {
	OrderNumber string `json:"orderNumber"`
	PayMethod   int64  `json:"payMethod"`
	UserId      string `json:"userId,optional"`
}

type PaymentResp struct {
	Default
	Payment
}

type ReOrderReq struct {
	Id     int64  `path:"id"`
	UserId string `json:"userId,optional"`
}

type ReOrderResp struct {
	Default
}

type ReminderReq struct {
	Id     int64  `path:"id"`
	UserId string `json:"userId,optional"`
}

type ReminderResp struct {
	Default
}

type Submit struct {
	Id          int64  `json:"id"`
	OrderNumber string `json:"orderNumber"`
	OrderAmount int64  `json:"orderAmount"`
	OrderTime   string `json:"orderTime"`
}

type SubmitReq struct {
	AddressId             int64  `json:"addressId"`
	PayMethod             int64  `json:"payMethod"`
	Remark                string `json:"remark"`
	EstimatedDeliveryTime string `json:"estimatedDeliveryTime"`
	DeliveryStatus        int64  `json:"deliveryStatus"`
	TablewareNumber       int64  `json:"tablewareNumber"`
	TablewareStatus       int64  `json:"tablewareStatus"`
	PackAmount            int64  `json:"packAmount"`
	Amount                int64  `json:"amount"`
	UserId                string `json:"userId,optional"`
}

type SubmitResp struct {
	Default
	Data struct {
		Id          int64  `json:"id"`
		OrderNumber string `json:"orderNumber"`
		OrderAmount int64  `json:"orderAmount"`
		OrderTime   string `json:"orderTime"`
	} `json:"data"`
}

type UnPayOrderCountReq struct {
	UserId string `json:"userId,optional"`
}

type UnPayOrderCountResp struct {
	Default
	Count int64 `json:"data"`
}

type WebsocketReq struct {
	UserId string `path:"userId"`
}

type WebsocketResp struct {
	Type    int    `json:"type"`
	Content string `json:"content"`
	OrderId int64  `json:"orderId"`
}
