// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"hanye/service/address/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: addAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: updateAddressByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: getAddressByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: deleteAddressByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/default",
					Handler: getDefaultAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/default",
					Handler: setDefaultAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: getAddressListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/user/address"),
	)
}
