// Code generated by goctl. DO NOT EDIT.
// Source: cart.proto

package server

import (
	"context"

	"hanye/service/cart/rpc/internal/logic"
	"hanye/service/cart/rpc/internal/svc"
	"hanye/service/cart/rpc/pb"
)

type CartServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCartServer
}

func NewCartServer(svcCtx *svc.ServiceContext) *CartServer {
	return &CartServer{
		svcCtx: svcCtx,
	}
}

func (s *CartServer) AddSubCart(ctx context.Context, in *pb.AddSubCartReq) (*pb.AddSubCartResp, error) {
	l := logic.NewAddSubCartLogic(ctx, s.svcCtx)
	return l.AddSubCart(in)
}

func (s *CartServer) GetCartList(ctx context.Context, in *pb.GetCartListReq) (*pb.GetCartListResp, error) {
	l := logic.NewGetCartListLogic(ctx, s.svcCtx)
	return l.GetCartList(in)
}

func (s *CartServer) CleanCart(ctx context.Context, in *pb.CleanCartReq) (*pb.CleanCartResp, error) {
	l := logic.NewCleanCartLogic(ctx, s.svcCtx)
	return l.CleanCart(in)
}
