// Code generated by goctl. DO NOT EDIT.
package types

type AddSubCartReq struct {
	UserId string `json:"userId,optional"`
	CartReq
}

type AddSubCartResp struct {
	Default
}

type Cart struct {
	Id         int    `json:"id"`
	Name       string `json:"name"`
	UserId     int    `json:"userId"`
	DishId     int    `json:"dishId"`
	SetmealId  int    `json:"setmealId"`
	DishFlavor string `json:"dishFlavor"`
	Number     int    `json:"number"`
	Amount     int    `json:"amount"`
	Pic        string `json:"pic"`
	CreateTime string `json:"createTime"`
}

type CartReq struct {
	DishId     int64  `json:"dishId,optional"`
	SetmealId  int64  `json:"setmealId,optional"`
	DishFlavor string `json:"dishFlavor,optional"`
}

type CleanCartReq struct {
	UserId string `json:"userId,optional"`
}

type CleanCartResp struct {
	Default
}

type Default struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type GetCartListReq struct {
	UserId string `json:"userId,optional"`
}

type GetCartListResp struct {
	Default
	Carts []*Cart `json:"data"`
}
