// Code generated by goctl. DO NOT EDIT.
// Source: cart.proto

package cart

import (
	"context"

	"hanye/service/cart/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddSubCartReq   = pb.AddSubCartReq
	AddSubCartResp  = pb.AddSubCartResp
	Cart            = pb.Cart
	CleanCartReq    = pb.CleanCartReq
	CleanCartResp   = pb.CleanCartResp
	GetCartListReq  = pb.GetCartListReq
	GetCartListResp = pb.GetCartListResp

	CartZrpcClient interface {
		AddSubCart(ctx context.Context, in *AddSubCartReq, opts ...grpc.CallOption) (*AddSubCartResp, error)
		GetCartList(ctx context.Context, in *GetCartListReq, opts ...grpc.CallOption) (*GetCartListResp, error)
		CleanCart(ctx context.Context, in *CleanCartReq, opts ...grpc.CallOption) (*CleanCartResp, error)
	}

	defaultCartZrpcClient struct {
		cli zrpc.Client
	}
)

func NewCartZrpcClient(cli zrpc.Client) CartZrpcClient {
	return &defaultCartZrpcClient{
		cli: cli,
	}
}

func (m *defaultCartZrpcClient) AddSubCart(ctx context.Context, in *AddSubCartReq, opts ...grpc.CallOption) (*AddSubCartResp, error) {
	client := pb.NewCartClient(m.cli.Conn())
	return client.AddSubCart(ctx, in, opts...)
}

func (m *defaultCartZrpcClient) GetCartList(ctx context.Context, in *GetCartListReq, opts ...grpc.CallOption) (*GetCartListResp, error) {
	client := pb.NewCartClient(m.cli.Conn())
	return client.GetCartList(ctx, in, opts...)
}

func (m *defaultCartZrpcClient) CleanCart(ctx context.Context, in *CleanCartReq, opts ...grpc.CallOption) (*CleanCartResp, error) {
	client := pb.NewCartClient(m.cli.Conn())
	return client.CleanCart(ctx, in, opts...)
}
