// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	ordersFieldNames          = builder.RawFieldNames(&Orders{})
	ordersRows                = strings.Join(ordersFieldNames, ",")
	ordersRowsExpectAutoSet   = strings.Join(stringx.Remove(ordersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	ordersRowsWithPlaceHolder = strings.Join(stringx.Remove(ordersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheHanyeOrdersIdPrefix     = "cache:hanye:orders:id:"
	cacheHanyeOrdersNumberPrefix = "cache:hanye:orders:number:"
)

type (
	ordersModel interface {
		Insert(ctx context.Context, data *Orders) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Orders, error)
		FindOneByNumber(ctx context.Context, number string) (*Orders, error)
		GetCountByUserId(ctx context.Context, userId string) (int64, error)
		QueryCondition(ctx context.Context, req *PageReq) (*[]*Orders, error)
		Update(ctx context.Context, data *Orders) error
		Delete(ctx context.Context, id int64) error
	}

	defaultOrdersModel struct {
		sqlc.CachedConn
		table string
	}

	PageReq struct {
		Page     int64
		PageSize int64
		Status   int64
		UserId string
	}
	Orders struct {
		Id                    int64        `db:"id"`                      // 主键
		Number                string       `db:"number"`                  // 订单号
		Status                int64        `db:"status"`                  // 订单状态 1待付款 2待接单 3已接单 4派送中 5已完成 6已取消 7退款
		UserId                string       `db:"user_id"`                 // 下单用户
		AddressBookId         int64        `db:"address_book_id"`         // 地址id
		OrderTime             time.Time    `db:"order_time"`              // 下单时间
		CheckoutTime          sql.NullTime `db:"checkout_time"`           // 结账时间
		PayMethod             int64        `db:"pay_method"`              // 支付方式 1微信,2支付宝
		PayStatus             int64        `db:"pay_status"`              // 支付状态 0未支付 1已支付 2退款
		Amount                float64      `db:"amount"`                  // 实收金额
		Remark                string       `db:"remark"`                  // 备注
		Phone                 string       `db:"phone"`                   // 手机号
		Address               string       `db:"address"`                 // 地址
		UserName              string       `db:"user_name"`               // 用户名称
		Consignee             string       `db:"consignee"`               // 收货人
		CancelReason          string       `db:"cancel_reason"`           // 订单取消原因
		RejectionReason       string       `db:"rejection_reason"`        // 订单拒绝原因
		CancelTime            sql.NullTime `db:"cancel_time"`             // 订单取消时间
		EstimatedDeliveryTime time.Time    `db:"estimated_delivery_time"` // 预计送达时间
		DeliveryStatus        int64        `db:"delivery_status"`         // 配送状态  1立即送出  0选择具体时间
		DeliveryTime          sql.NullTime `db:"delivery_time"`           // 送达时间
		PackAmount            int64        `db:"pack_amount"`             // 打包费
		TablewareNumber       int64        `db:"tableware_number"`        // 餐具数量
		TablewareStatus       int64        `db:"tableware_status"`        // 餐具数量状态  1按餐量提供  0选择具体数量
	}
)

func newOrdersModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOrdersModel {
	return &defaultOrdersModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`orders`",
	}
}

func (m *defaultOrdersModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	hanyeOrdersIdKey := fmt.Sprintf("%s%v", cacheHanyeOrdersIdPrefix, id)
	hanyeOrdersNumberKey := fmt.Sprintf("%s%v", cacheHanyeOrdersNumberPrefix, data.Number)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, hanyeOrdersIdKey, hanyeOrdersNumberKey)
	return err
}

func (m *defaultOrdersModel) FindOne(ctx context.Context, id int64) (*Orders, error) {
	hanyeOrdersIdKey := fmt.Sprintf("%s%v", cacheHanyeOrdersIdPrefix, id)
	var resp Orders
	err := m.QueryRowCtx(ctx, &resp, hanyeOrdersIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", ordersRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrdersModel) GetCountByUserId(ctx context.Context, userId string) (int64, error) {
	var count int64
	query := fmt.Sprintf("select count(*) from %s where `user_id` = ? and `status` = 1", m.table)
	err := m.QueryRowNoCacheCtx(ctx, &count, query, userId)
	if err != nil {
		return 0, err
	}
	fmt.Println(count)
	return count, nil
}

func (m *defaultOrdersModel) FindOneByNumber(ctx context.Context, number string) (*Orders, error) {
	hanyeOrdersNumberKey := fmt.Sprintf("%s%v", cacheHanyeOrdersNumberPrefix, number)
	var resp Orders
	err := m.QueryRowIndexCtx(ctx, &resp, hanyeOrdersNumberKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `number` = ? limit 1", ordersRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, number); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrdersModel) QueryCondition(ctx context.Context, req *PageReq) (*[]*Orders, error) {
	var resp []*Orders
	//offest := (req.Page - 1) * req.PageSize
	//limit := req.PageSize
	var query string
	if req.Status != 0 {
		query = fmt.Sprintf("select * from %s where `status` = ? and `user_id` = ?", m.table)
		err := m.QueryRowsNoCacheCtx(ctx, &resp, query, req.Status, req.UserId)
		switch err {
		case nil:
			return &resp, nil
		case sqlc.ErrNotFound:
			return nil, ErrNotFound
		default:
			return nil, err
		}
	}else {
			query = fmt.Sprintf("select * from %s where `user_id` = ?", m.table)
			err := m.QueryRowsNoCacheCtx(ctx, &resp, query, req.UserId)
			switch err {
			case nil:
				return &resp, nil
			case sqlc.ErrNotFound:
				return nil, ErrNotFound
			default:
				return nil, err
		}
	}
}

func (m *defaultOrdersModel) Insert(ctx context.Context, data *Orders) (sql.Result, error) {
	hanyeOrdersIdKey := fmt.Sprintf("%s%v", cacheHanyeOrdersIdPrefix, data.Id)
	hanyeOrdersNumberKey := fmt.Sprintf("%s%v", cacheHanyeOrdersNumberPrefix, data.Number)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, ordersRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Number, data.Status, data.UserId, data.AddressBookId, data.OrderTime, data.CheckoutTime, data.PayMethod, data.PayStatus, data.Amount, data.Remark, data.Phone, data.Address, data.UserName, data.Consignee, data.CancelReason, data.RejectionReason, data.CancelTime, data.EstimatedDeliveryTime, data.DeliveryStatus, data.DeliveryTime, data.PackAmount, data.TablewareNumber, data.TablewareStatus)
	}, hanyeOrdersIdKey, hanyeOrdersNumberKey)
	return ret, err
}

func (m *defaultOrdersModel) Update(ctx context.Context, newData *Orders) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	hanyeOrdersIdKey := fmt.Sprintf("%s%v", cacheHanyeOrdersIdPrefix, data.Id)
	hanyeOrdersNumberKey := fmt.Sprintf("%s%v", cacheHanyeOrdersNumberPrefix, data.Number)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, ordersRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Number, newData.Status, newData.UserId, newData.AddressBookId, newData.OrderTime, newData.CheckoutTime, newData.PayMethod, newData.PayStatus, newData.Amount, newData.Remark, newData.Phone, newData.Address, newData.UserName, newData.Consignee, newData.CancelReason, newData.RejectionReason, newData.CancelTime, newData.EstimatedDeliveryTime, newData.DeliveryStatus, newData.DeliveryTime, newData.PackAmount, newData.TablewareNumber, newData.TablewareStatus, newData.Id)
	}, hanyeOrdersIdKey, hanyeOrdersNumberKey)
	return err
}

func (m *defaultOrdersModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheHanyeOrdersIdPrefix, primary)
}

func (m *defaultOrdersModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", ordersRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOrdersModel) tableName() string {
	return m.table
}
