// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"hanye/service/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPut,
					Path:    "/cancel/:id",
					Handler: cancelHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/historyOrders",
					Handler: historyOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/orderDetail/:id",
					Handler: orderDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/payment",
					Handler: paymentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/reOrder/:id",
					Handler: reOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/reminder/:id",
					Handler: reminderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/submit",
					Handler: submitHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/unPayOrderCount",
					Handler: unPayOrderCountHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/user/order"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:userId",
				Handler: websocketHandler(serverCtx),
			},
		},
		rest.WithPrefix("/ws"),
	)
}
