// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	categoryFieldNames          = builder.RawFieldNames(&Category{})
	categoryRows                = strings.Join(categoryFieldNames, ",")
	categoryRowsExpectAutoSet   = strings.Join(stringx.Remove(categoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	categoryRowsWithPlaceHolder = strings.Join(stringx.Remove(categoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheHanyeCategoryIdPrefix   = "cache:hanye:category:id:"
	cacheHanyeCategoryNamePrefix = "cache:hanye:category:name:"
	cacheHanyeCategoryPrefix     = "cache:hanye:category"
)

type (
	categoryModel interface {
		Insert(ctx context.Context, data *Category) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Category, error)
		FindOneByName(ctx context.Context, name string) (*Category, error)
		GetCategories(ctx context.Context) (*[]*Category, error)
		Update(ctx context.Context, data *Category) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCategoryModel struct {
		sqlc.CachedConn
		table string
	}

	Category struct {
		Id         int64     `db:"id"`
		Name       string    `db:"name"`
		Type       int64     `db:"type"`
		Sort       int64     `db:"sort"`
		Status     int64     `db:"status"`
		CreateUser int64     `db:"create_user"`
		UpdateUser int64     `db:"update_user"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newCategoryModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCategoryModel {
	return &defaultCategoryModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`category`",
	}
}

func (m *defaultCategoryModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	hanyeCategoryIdKey := fmt.Sprintf("%s%v", cacheHanyeCategoryIdPrefix, id)
	hanyeCategoryNameKey := fmt.Sprintf("%s%v", cacheHanyeCategoryNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, hanyeCategoryIdKey, hanyeCategoryNameKey)
	return err
}

func (m *defaultCategoryModel) FindOne(ctx context.Context, id int64) (*Category, error) {
	hanyeCategoryIdKey := fmt.Sprintf("%s%v", cacheHanyeCategoryIdPrefix, id)
	var resp Category
	err := m.QueryRowCtx(ctx, &resp, hanyeCategoryIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", categoryRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCategoryModel) FindOneByName(ctx context.Context, name string) (*Category, error) {
	hanyeCategoryNameKey := fmt.Sprintf("%s%v", cacheHanyeCategoryNamePrefix, name)
	var resp Category
	err := m.QueryRowIndexCtx(ctx, &resp, hanyeCategoryNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", categoryRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCategoryModel) GetCategories(ctx context.Context) (*[]*Category, error) {
	var resp []*Category
	m.GetCacheCtx(ctx, cacheHanyeCategoryPrefix, &resp)
	if len(resp) != 0 {
		return &resp, nil
	}
	query := fmt.Sprintf("select * from %s",  m.table)
	err := m.QueryRowsNoCacheCtx(ctx, &resp, query)
	switch err {
	case nil:
		m.SetCacheCtx(ctx, cacheHanyeCategoryPrefix, resp)
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCategoryModel) Insert(ctx context.Context, data *Category) (sql.Result, error) {
	hanyeCategoryIdKey := fmt.Sprintf("%s%v", cacheHanyeCategoryIdPrefix, data.Id)
	hanyeCategoryNameKey := fmt.Sprintf("%s%v", cacheHanyeCategoryNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, categoryRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Type, data.Sort, data.Status, data.CreateUser, data.UpdateUser)
	}, hanyeCategoryIdKey, hanyeCategoryNameKey)
	return ret, err
}

func (m *defaultCategoryModel) Update(ctx context.Context, newData *Category) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	hanyeCategoryIdKey := fmt.Sprintf("%s%v", cacheHanyeCategoryIdPrefix, data.Id)
	hanyeCategoryNameKey := fmt.Sprintf("%s%v", cacheHanyeCategoryNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, categoryRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Type, newData.Sort, newData.Status, newData.CreateUser, newData.UpdateUser, newData.Id)
	}, hanyeCategoryIdKey, hanyeCategoryNameKey)
	return err
}

func (m *defaultCategoryModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheHanyeCategoryIdPrefix, primary)
}

func (m *defaultCategoryModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", categoryRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCategoryModel) tableName() string {
	return m.table
}
