// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	setmealDishFieldNames          = builder.RawFieldNames(&SetmealDish{})
	setmealDishRows                = strings.Join(setmealDishFieldNames, ",")
	setmealDishRowsExpectAutoSet   = strings.Join(stringx.Remove(setmealDishFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	setmealDishRowsWithPlaceHolder = strings.Join(stringx.Remove(setmealDishFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheHanyeSetmealDishIdPrefix = "cache:hanye:setmealDish:id:"
	cacheHanyeSetmealDishSetmealIdPrefix = "cache:hanye:setmealDish:setmealid:"
)

type (
	setmealDishModel interface {
		Insert(ctx context.Context, data *SetmealDish) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SetmealDish, error)
		FindBySetmealId(ctx context.Context, id int64) (*[]*SetmealDish, error)
		//FindDishIdsById(ctx context.Context, id int64) (*[]int64, error)
		Update(ctx context.Context, data *SetmealDish) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSetmealDishModel struct {
		sqlc.CachedConn
		table string
	}

	SetmealDish struct {
		Id        int64   `db:"id"`
		Name      string  `db:"name"`
		Price     float64 `db:"price"`
		Copies    int64   `db:"copies"`
		DishId    int64   `db:"dish_id"`
		SetmealId int64   `db:"setmeal_id"`
	}
)

func newSetmealDishModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSetmealDishModel {
	return &defaultSetmealDishModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`setmeal_dish`",
	}
}

func (m *defaultSetmealDishModel) Delete(ctx context.Context, id int64) error {
	hanyeSetmealDishIdKey := fmt.Sprintf("%s%v", cacheHanyeSetmealDishIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, hanyeSetmealDishIdKey)
	return err
}

func (m *defaultSetmealDishModel) FindOne(ctx context.Context, id int64) (*SetmealDish, error) {
	hanyeSetmealDishIdKey := fmt.Sprintf("%s%v", cacheHanyeSetmealDishIdPrefix, id)
	var resp SetmealDish
	err := m.QueryRowCtx(ctx, &resp, hanyeSetmealDishIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", setmealDishRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSetmealDishModel) FindBySetmealId(ctx context.Context, id int64) (*[]*SetmealDish, error) {
	cacheHanyeSetmealDishSetmealId := fmt.Sprintf("%s%v", cacheHanyeSetmealDishSetmealIdPrefix, id)
	var resp []*SetmealDish
	m.GetCacheCtx(ctx, cacheHanyeSetmealDishSetmealId, &resp)
	if len(resp) != 0 {
		return &resp, nil
	}
	query := fmt.Sprintf("select * from %s where `setmeal_id` = ?",  m.table)
	err := m.QueryRowsNoCacheCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		m.SetCacheCtx(ctx, cacheHanyeSetmealDishSetmealIdPrefix, resp)
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

//func (m *defaultSetmealDishModel) FindDishIdsById(ctx context.Context, id int64) (*[]int64, error) {
//	setmealDishes, err := m.FindBySetmealId(ctx, id)
//	if err != nil {
//		return nil, err
//	}
//	var res []int64
//	for _,v := range *setmealDishes {
//		res = append(res, v.DishId)
//	}
//	return &res,nil
//}

func (m *defaultSetmealDishModel) Insert(ctx context.Context, data *SetmealDish) (sql.Result, error) {
	hanyeSetmealDishIdKey := fmt.Sprintf("%s%v", cacheHanyeSetmealDishIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, setmealDishRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Price, data.Copies, data.DishId, data.SetmealId)
	}, hanyeSetmealDishIdKey)
	return ret, err
}

func (m *defaultSetmealDishModel) Update(ctx context.Context, data *SetmealDish) error {
	hanyeSetmealDishIdKey := fmt.Sprintf("%s%v", cacheHanyeSetmealDishIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, setmealDishRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Price, data.Copies, data.DishId, data.SetmealId, data.Id)
	}, hanyeSetmealDishIdKey)
	return err
}

func (m *defaultSetmealDishModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheHanyeSetmealDishIdPrefix, primary)
}

func (m *defaultSetmealDishModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", setmealDishRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSetmealDishModel) tableName() string {
	return m.table
}
