// Code generated by goctl. DO NOT EDIT.
package types

type Address struct {
	UserId       string `json:"userId,optional"`
	Consignee    string `json:"consignee"`
	Phone        string `json:"phone"`
	Gender       int64  `json:"gender"`
	ProvinceCode string `json:"provinceCode"`
	ProvinceName string `json:"provinceName"`
	CityCode     string `json:"cityCode"`
	CityName     string `json:"cityName"`
	DistrictCode string `json:"districtCode"`
	DistrictName string `json:"districtName"`
	Detail       string `json:"detail"`
	Label        string `json:"label"`
	IsDefault    int64  `json:"isDefault,optional"`
}

type AddressReq struct {
	Address
}

type AddressResp struct {
	Default
}

type AddressWithId struct {
	Id int64 `json:"id"`
	Address
}

type Default struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type DeleteAddressByIdReq struct {
	Id     int64  `path:"id"`
	UserId string `json:"userId,optional"`
}

type DeleteAddressByIdResp struct {
	Default
}

type GetAddressByIdReq struct {
	Id     int64  `path:"id"`
	UserId string `json:"userId,optional"`
}

type GetAddressByIdResp struct {
	Default
	AddressInfo *AddressWithId `json:"data"`
}

type GetAddressListReq struct {
	UserId string `json:"userId,optional"`
}

type GetAddressListResp struct {
	Default
	Addresses []*AddressWithId `json:"data"`
}

type GetDefaultAddressReq struct {
	UserId string `json:"userId,optional"`
}

type GetDefaultAddressResp struct {
	Default
	AddressInfo *AddressWithId `json:"data"`
}

type SetDefaultAddressReq struct {
	Id     int64  `json:"id"`
	UserId string `json:"userId,optional"`
}

type SetDefaultAddressResp struct {
	Default
}

type UpdateAddressByIdReq struct {
	AddressWithId
	UserId string `json:"userId,optional"`
}

type UpdateAddressByIdResp struct {
	Default
}
