// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: meal.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// model
type Category struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type       int64  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Sort       int64  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Status     int64  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreateUser int64  `protobuf:"varint,6,opt,name=createUser,proto3" json:"createUser,omitempty"`
	UpdateUser int64  `protobuf:"varint,7,opt,name=updateUser,proto3" json:"updateUser,omitempty"`
	CreateTime string `protobuf:"bytes,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime string `protobuf:"bytes,9,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
}

func (x *Category) Reset() {
	*x = Category{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Category) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *Category) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Category) GetCreateUser() int64 {
	if x != nil {
		return x.CreateUser
	}
	return 0
}

func (x *Category) GetUpdateUser() int64 {
	if x != nil {
		return x.UpdateUser
	}
	return 0
}

func (x *Category) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Category) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type GetCategoryListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCategoryListReq) Reset() {
	*x = GetCategoryListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCategoryListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryListReq) ProtoMessage() {}

func (x *GetCategoryListReq) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryListReq.ProtoReflect.Descriptor instead.
func (*GetCategoryListReq) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{1}
}

type GetCategoryListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Categories []*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	Code       int64       `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GetCategoryListResp) Reset() {
	*x = GetCategoryListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCategoryListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryListResp) ProtoMessage() {}

func (x *GetCategoryListResp) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryListResp.ProtoReflect.Descriptor instead.
func (*GetCategoryListResp) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{2}
}

func (x *GetCategoryListResp) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *GetCategoryListResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// model
type Setmeal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pic        string  `protobuf:"bytes,3,opt,name=pic,proto3" json:"pic,omitempty"`
	Detail     string  `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Status     int64   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreateUser int64   `protobuf:"varint,6,opt,name=createUser,proto3" json:"createUser,omitempty"`
	UpdateUser int64   `protobuf:"varint,7,opt,name=updateUser,proto3" json:"updateUser,omitempty"`
	CreateTime string  `protobuf:"bytes,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime string  `protobuf:"bytes,9,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Price      float64 `protobuf:"fixed64,10,opt,name=price,proto3" json:"price,omitempty"`
	CategoryId int64   `protobuf:"varint,11,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
}

func (x *Setmeal) Reset() {
	*x = Setmeal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Setmeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setmeal) ProtoMessage() {}

func (x *Setmeal) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setmeal.ProtoReflect.Descriptor instead.
func (*Setmeal) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{3}
}

func (x *Setmeal) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Setmeal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Setmeal) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *Setmeal) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Setmeal) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Setmeal) GetCreateUser() int64 {
	if x != nil {
		return x.CreateUser
	}
	return 0
}

func (x *Setmeal) GetUpdateUser() int64 {
	if x != nil {
		return x.UpdateUser
	}
	return 0
}

func (x *Setmeal) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Setmeal) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *Setmeal) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Setmeal) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type GetSetmealsByCategoryIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryId int64 `protobuf:"varint,1,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
}

func (x *GetSetmealsByCategoryIdReq) Reset() {
	*x = GetSetmealsByCategoryIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSetmealsByCategoryIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSetmealsByCategoryIdReq) ProtoMessage() {}

func (x *GetSetmealsByCategoryIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSetmealsByCategoryIdReq.ProtoReflect.Descriptor instead.
func (*GetSetmealsByCategoryIdReq) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{4}
}

func (x *GetSetmealsByCategoryIdReq) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type GetSetmealsByCategoryIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Setmeals []*Setmeal `protobuf:"bytes,1,rep,name=setmeals,proto3" json:"setmeals,omitempty"`
	Code     int64      `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GetSetmealsByCategoryIdResp) Reset() {
	*x = GetSetmealsByCategoryIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSetmealsByCategoryIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSetmealsByCategoryIdResp) ProtoMessage() {}

func (x *GetSetmealsByCategoryIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSetmealsByCategoryIdResp.ProtoReflect.Descriptor instead.
func (*GetSetmealsByCategoryIdResp) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{5}
}

func (x *GetSetmealsByCategoryIdResp) GetSetmeals() []*Setmeal {
	if x != nil {
		return x.Setmeals
	}
	return nil
}

func (x *GetSetmealsByCategoryIdResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// model
type SetmealDishes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pic       string `protobuf:"bytes,3,opt,name=pic,proto3" json:"pic,omitempty"`
	Detail    string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Copies    int64  `protobuf:"varint,5,opt,name=copies,proto3" json:"copies,omitempty"`
	SetmealId int64  `protobuf:"varint,6,opt,name=setmealId,proto3" json:"setmealId,omitempty"`
	DishId    int64  `protobuf:"varint,7,opt,name=dishId,proto3" json:"dishId,omitempty"`
}

func (x *SetmealDishes) Reset() {
	*x = SetmealDishes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetmealDishes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetmealDishes) ProtoMessage() {}

func (x *SetmealDishes) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetmealDishes.ProtoReflect.Descriptor instead.
func (*SetmealDishes) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{6}
}

func (x *SetmealDishes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetmealDishes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetmealDishes) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *SetmealDishes) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *SetmealDishes) GetCopies() int64 {
	if x != nil {
		return x.Copies
	}
	return 0
}

func (x *SetmealDishes) GetSetmealId() int64 {
	if x != nil {
		return x.SetmealId
	}
	return 0
}

func (x *SetmealDishes) GetDishId() int64 {
	if x != nil {
		return x.DishId
	}
	return 0
}

type SetmealWithDishes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pic           string           `protobuf:"bytes,3,opt,name=pic,proto3" json:"pic,omitempty"`
	Detail        string           `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Status        int64            `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	UpdateTime    string           `protobuf:"bytes,6,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Price         float64          `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	CategoryId    int64            `protobuf:"varint,8,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	SetmealDishes []*SetmealDishes `protobuf:"bytes,9,rep,name=setmealDishes,proto3" json:"setmealDishes,omitempty"`
}

func (x *SetmealWithDishes) Reset() {
	*x = SetmealWithDishes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetmealWithDishes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetmealWithDishes) ProtoMessage() {}

func (x *SetmealWithDishes) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetmealWithDishes.ProtoReflect.Descriptor instead.
func (*SetmealWithDishes) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{7}
}

func (x *SetmealWithDishes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetmealWithDishes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetmealWithDishes) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *SetmealWithDishes) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *SetmealWithDishes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SetmealWithDishes) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *SetmealWithDishes) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SetmealWithDishes) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *SetmealWithDishes) GetSetmealDishes() []*SetmealDishes {
	if x != nil {
		return x.SetmealDishes
	}
	return nil
}

type GetSetmealsByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SetmealId int64 `protobuf:"varint,1,opt,name=setmealId,proto3" json:"setmealId,omitempty"`
}

func (x *GetSetmealsByIdReq) Reset() {
	*x = GetSetmealsByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSetmealsByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSetmealsByIdReq) ProtoMessage() {}

func (x *GetSetmealsByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSetmealsByIdReq.ProtoReflect.Descriptor instead.
func (*GetSetmealsByIdReq) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{8}
}

func (x *GetSetmealsByIdReq) GetSetmealId() int64 {
	if x != nil {
		return x.SetmealId
	}
	return 0
}

type GetSetmealsByIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Setmeal *SetmealWithDishes `protobuf:"bytes,1,opt,name=setmeal,proto3" json:"setmeal,omitempty"`
	Code    int64              `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GetSetmealsByIdResp) Reset() {
	*x = GetSetmealsByIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSetmealsByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSetmealsByIdResp) ProtoMessage() {}

func (x *GetSetmealsByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSetmealsByIdResp.ProtoReflect.Descriptor instead.
func (*GetSetmealsByIdResp) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{9}
}

func (x *GetSetmealsByIdResp) GetSetmeal() *SetmealWithDishes {
	if x != nil {
		return x.Setmeal
	}
	return nil
}

func (x *GetSetmealsByIdResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type DishSimple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pic    string `protobuf:"bytes,2,opt,name=pic,proto3" json:"pic,omitempty"`
	Detail string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Copies int64  `protobuf:"varint,4,opt,name=copies,proto3" json:"copies,omitempty"`
}

func (x *DishSimple) Reset() {
	*x = DishSimple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DishSimple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishSimple) ProtoMessage() {}

func (x *DishSimple) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishSimple.ProtoReflect.Descriptor instead.
func (*DishSimple) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{10}
}

func (x *DishSimple) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DishSimple) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *DishSimple) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *DishSimple) GetCopies() int64 {
	if x != nil {
		return x.Copies
	}
	return 0
}

type GetDishSimplesByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SetmealId int64 `protobuf:"varint,1,opt,name=setmealId,proto3" json:"setmealId,omitempty"`
}

func (x *GetDishSimplesByIdReq) Reset() {
	*x = GetDishSimplesByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDishSimplesByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishSimplesByIdReq) ProtoMessage() {}

func (x *GetDishSimplesByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishSimplesByIdReq.ProtoReflect.Descriptor instead.
func (*GetDishSimplesByIdReq) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{11}
}

func (x *GetDishSimplesByIdReq) GetSetmealId() int64 {
	if x != nil {
		return x.SetmealId
	}
	return 0
}

type GetDishSimplesByIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dishes []*DishSimple `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
	Code   int64         `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GetDishSimplesByIdResp) Reset() {
	*x = GetDishSimplesByIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDishSimplesByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishSimplesByIdResp) ProtoMessage() {}

func (x *GetDishSimplesByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishSimplesByIdResp.ProtoReflect.Descriptor instead.
func (*GetDishSimplesByIdResp) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{12}
}

func (x *GetDishSimplesByIdResp) GetDishes() []*DishSimple {
	if x != nil {
		return x.Dishes
	}
	return nil
}

func (x *GetDishSimplesByIdResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// model
type Flavor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	List   string `protobuf:"bytes,3,opt,name=list,proto3" json:"list,omitempty"`
	DishId int64  `protobuf:"varint,4,opt,name=dishId,proto3" json:"dishId,omitempty"`
}

func (x *Flavor) Reset() {
	*x = Flavor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Flavor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flavor) ProtoMessage() {}

func (x *Flavor) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flavor.ProtoReflect.Descriptor instead.
func (*Flavor) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{13}
}

func (x *Flavor) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Flavor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Flavor) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *Flavor) GetDishId() int64 {
	if x != nil {
		return x.DishId
	}
	return 0
}

type Dish struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pic        string    `protobuf:"bytes,3,opt,name=pic,proto3" json:"pic,omitempty"`
	Detail     string    `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Status     int64     `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Price      float64   `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	CategoryId int64     `protobuf:"varint,7,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	UpdateTime string    `protobuf:"bytes,8,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Flavors    []*Flavor `protobuf:"bytes,9,rep,name=flavors,proto3" json:"flavors,omitempty"`
}

func (x *Dish) Reset() {
	*x = Dish{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dish) ProtoMessage() {}

func (x *Dish) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dish.ProtoReflect.Descriptor instead.
func (*Dish) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{14}
}

func (x *Dish) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dish) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dish) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *Dish) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Dish) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Dish) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Dish) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Dish) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *Dish) GetFlavors() []*Flavor {
	if x != nil {
		return x.Flavors
	}
	return nil
}

type GetDishesByCategoryIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryId int64 `protobuf:"varint,1,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
}

func (x *GetDishesByCategoryIdReq) Reset() {
	*x = GetDishesByCategoryIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDishesByCategoryIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesByCategoryIdReq) ProtoMessage() {}

func (x *GetDishesByCategoryIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesByCategoryIdReq.ProtoReflect.Descriptor instead.
func (*GetDishesByCategoryIdReq) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{15}
}

func (x *GetDishesByCategoryIdReq) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type GetDishesByCategoryIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dishes []*Dish `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
	Code   int64   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GetDishesByCategoryIdResp) Reset() {
	*x = GetDishesByCategoryIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDishesByCategoryIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesByCategoryIdResp) ProtoMessage() {}

func (x *GetDishesByCategoryIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesByCategoryIdResp.ProtoReflect.Descriptor instead.
func (*GetDishesByCategoryIdResp) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{16}
}

func (x *GetDishesByCategoryIdResp) GetDishes() []*Dish {
	if x != nil {
		return x.Dishes
	}
	return nil
}

func (x *GetDishesByCategoryIdResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type GetDishesByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DishId int64 `protobuf:"varint,1,opt,name=dishId,proto3" json:"dishId,omitempty"`
}

func (x *GetDishesByIdReq) Reset() {
	*x = GetDishesByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDishesByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesByIdReq) ProtoMessage() {}

func (x *GetDishesByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesByIdReq.ProtoReflect.Descriptor instead.
func (*GetDishesByIdReq) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{17}
}

func (x *GetDishesByIdReq) GetDishId() int64 {
	if x != nil {
		return x.DishId
	}
	return 0
}

type GetDishesByIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dish *Dish `protobuf:"bytes,1,opt,name=dish,proto3" json:"dish,omitempty"`
	Code int64 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GetDishesByIdResp) Reset() {
	*x = GetDishesByIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDishesByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesByIdResp) ProtoMessage() {}

func (x *GetDishesByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesByIdResp.ProtoReflect.Descriptor instead.
func (*GetDishesByIdResp) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{18}
}

func (x *GetDishesByIdResp) GetDish() *Dish {
	if x != nil {
		return x.Dish
	}
	return nil
}

func (x *GetDishesByIdResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_meal_proto protoreflect.FileDescriptor

var file_meal_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x65, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0xee, 0x01, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x57, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c,
	0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0xa5, 0x02, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x6d, 0x65, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70,
	0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x53,
	0x65, 0x74, 0x6d, 0x65, 0x61, 0x6c, 0x73, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x53, 0x65, 0x74,
	0x6d, 0x65, 0x61, 0x6c, 0x73, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x27, 0x0a, 0x08, 0x73, 0x65, 0x74, 0x6d, 0x65, 0x61, 0x6c,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x74,
	0x6d, 0x65, 0x61, 0x6c, 0x52, 0x08, 0x73, 0x65, 0x74, 0x6d, 0x65, 0x61, 0x6c, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x22, 0xab, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x6d, 0x65, 0x61, 0x6c, 0x44, 0x69,
	0x73, 0x68, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x63, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x70, 0x69, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x70, 0x69, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65,
	0x74, 0x6d, 0x65, 0x61, 0x6c, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73,
	0x65, 0x74, 0x6d, 0x65, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x73, 0x68,
	0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x69, 0x73, 0x68, 0x49, 0x64,
	0x22, 0x88, 0x02, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x6d, 0x65, 0x61, 0x6c, 0x57, 0x69, 0x74, 0x68,
	0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69,
	0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x49, 0x64, 0x12, 0x37, 0x0a, 0x0d, 0x73, 0x65, 0x74, 0x6d, 0x65, 0x61, 0x6c, 0x44, 0x69, 0x73,
	0x68, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x53,
	0x65, 0x74, 0x6d, 0x65, 0x61, 0x6c, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x0d, 0x73, 0x65,
	0x74, 0x6d, 0x65, 0x61, 0x6c, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x22, 0x32, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x53, 0x65, 0x74, 0x6d, 0x65, 0x61, 0x6c, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x74, 0x6d, 0x65, 0x61, 0x6c, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x74, 0x6d, 0x65, 0x61, 0x6c, 0x49, 0x64, 0x22,
	0x5a, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x65, 0x74, 0x6d, 0x65, 0x61, 0x6c, 0x73, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x07, 0x73, 0x65, 0x74, 0x6d, 0x65, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x74,
	0x6d, 0x65, 0x61, 0x6c, 0x57, 0x69, 0x74, 0x68, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x07,
	0x73, 0x65, 0x74, 0x6d, 0x65, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x62, 0x0a, 0x0a, 0x44,
	0x69, 0x73, 0x68, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x63, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x70, 0x69, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x70, 0x69, 0x65, 0x73, 0x22,
	0x35, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65,
	0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x74, 0x6d,
	0x65, 0x61, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x74,
	0x6d, 0x65, 0x61, 0x6c, 0x49, 0x64, 0x22, 0x54, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73,
	0x68, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x26, 0x0a, 0x06, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x73, 0x68, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65,
	0x52, 0x06, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x58, 0x0a, 0x06,
	0x46, 0x6c, 0x61, 0x76, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x64, 0x69, 0x73, 0x68, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x64, 0x69, 0x73, 0x68, 0x49, 0x64, 0x22, 0xe8, 0x01, 0x0a, 0x04, 0x44, 0x69, 0x73, 0x68, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x70, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x07, 0x66,
	0x6c, 0x61, 0x76, 0x6f, 0x72, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70,
	0x62, 0x2e, 0x46, 0x6c, 0x61, 0x76, 0x6f, 0x72, 0x52, 0x07, 0x66, 0x6c, 0x61, 0x76, 0x6f, 0x72,
	0x73, 0x22, 0x3a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x42, 0x79,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x22, 0x51, 0x0a,
	0x19, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x06, 0x64, 0x69,
	0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e,
	0x44, 0x69, 0x73, 0x68, 0x52, 0x06, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0x2a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x73, 0x68, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x69, 0x73, 0x68, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x1c, 0x0a, 0x04, 0x64, 0x69, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x73, 0x68, 0x52, 0x04, 0x64, 0x69, 0x73, 0x68, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x32, 0xcb, 0x03, 0x0a, 0x04, 0x6d, 0x65, 0x61, 0x6c, 0x12, 0x42, 0x0a, 0x0f,
	0x67, 0x65, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x16, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x5a, 0x0a, 0x17, 0x67, 0x65, 0x74, 0x53, 0x65, 0x74, 0x6d, 0x65, 0x61, 0x6c, 0x73, 0x42,
	0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1e, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x74, 0x6d, 0x65, 0x61, 0x6c, 0x73, 0x42, 0x79, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x74, 0x6d, 0x65, 0x61, 0x6c, 0x73, 0x42, 0x79, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x42, 0x0a, 0x0f,
	0x67, 0x65, 0x74, 0x53, 0x65, 0x74, 0x6d, 0x65, 0x61, 0x6c, 0x73, 0x42, 0x79, 0x49, 0x64, 0x12,
	0x16, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x74, 0x6d, 0x65, 0x61, 0x6c, 0x73,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x65, 0x74, 0x6d, 0x65, 0x61, 0x6c, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x4b, 0x0a, 0x12, 0x67, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x53, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x44,
	0x69, 0x73, 0x68, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x53, 0x69,
	0x6d, 0x70, 0x6c, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x54, 0x0a,
	0x15, 0x67, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x44,
	0x69, 0x73, 0x68, 0x65, 0x73, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73,
	0x68, 0x65, 0x73, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73,
	0x42, 0x79, 0x49, 0x64, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73,
	0x68, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_meal_proto_rawDescOnce sync.Once
	file_meal_proto_rawDescData = file_meal_proto_rawDesc
)

func file_meal_proto_rawDescGZIP() []byte {
	file_meal_proto_rawDescOnce.Do(func() {
		file_meal_proto_rawDescData = protoimpl.X.CompressGZIP(file_meal_proto_rawDescData)
	})
	return file_meal_proto_rawDescData
}

var file_meal_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_meal_proto_goTypes = []any{
	(*Category)(nil),                    // 0: pb.Category
	(*GetCategoryListReq)(nil),          // 1: pb.GetCategoryListReq
	(*GetCategoryListResp)(nil),         // 2: pb.GetCategoryListResp
	(*Setmeal)(nil),                     // 3: pb.Setmeal
	(*GetSetmealsByCategoryIdReq)(nil),  // 4: pb.GetSetmealsByCategoryIdReq
	(*GetSetmealsByCategoryIdResp)(nil), // 5: pb.GetSetmealsByCategoryIdResp
	(*SetmealDishes)(nil),               // 6: pb.SetmealDishes
	(*SetmealWithDishes)(nil),           // 7: pb.SetmealWithDishes
	(*GetSetmealsByIdReq)(nil),          // 8: pb.GetSetmealsByIdReq
	(*GetSetmealsByIdResp)(nil),         // 9: pb.GetSetmealsByIdResp
	(*DishSimple)(nil),                  // 10: pb.DishSimple
	(*GetDishSimplesByIdReq)(nil),       // 11: pb.GetDishSimplesByIdReq
	(*GetDishSimplesByIdResp)(nil),      // 12: pb.GetDishSimplesByIdResp
	(*Flavor)(nil),                      // 13: pb.Flavor
	(*Dish)(nil),                        // 14: pb.Dish
	(*GetDishesByCategoryIdReq)(nil),    // 15: pb.GetDishesByCategoryIdReq
	(*GetDishesByCategoryIdResp)(nil),   // 16: pb.GetDishesByCategoryIdResp
	(*GetDishesByIdReq)(nil),            // 17: pb.GetDishesByIdReq
	(*GetDishesByIdResp)(nil),           // 18: pb.GetDishesByIdResp
}
var file_meal_proto_depIdxs = []int32{
	0,  // 0: pb.GetCategoryListResp.categories:type_name -> pb.Category
	3,  // 1: pb.GetSetmealsByCategoryIdResp.setmeals:type_name -> pb.Setmeal
	6,  // 2: pb.SetmealWithDishes.setmealDishes:type_name -> pb.SetmealDishes
	7,  // 3: pb.GetSetmealsByIdResp.setmeal:type_name -> pb.SetmealWithDishes
	10, // 4: pb.GetDishSimplesByIdResp.dishes:type_name -> pb.DishSimple
	13, // 5: pb.Dish.flavors:type_name -> pb.Flavor
	14, // 6: pb.GetDishesByCategoryIdResp.dishes:type_name -> pb.Dish
	14, // 7: pb.GetDishesByIdResp.dish:type_name -> pb.Dish
	1,  // 8: pb.meal.getCategoryList:input_type -> pb.GetCategoryListReq
	4,  // 9: pb.meal.getSetmealsByCategoryId:input_type -> pb.GetSetmealsByCategoryIdReq
	8,  // 10: pb.meal.getSetmealsById:input_type -> pb.GetSetmealsByIdReq
	11, // 11: pb.meal.getDishSimplesById:input_type -> pb.GetDishSimplesByIdReq
	15, // 12: pb.meal.getDishesByCategoryId:input_type -> pb.GetDishesByCategoryIdReq
	17, // 13: pb.meal.getDishesById:input_type -> pb.GetDishesByIdReq
	2,  // 14: pb.meal.getCategoryList:output_type -> pb.GetCategoryListResp
	5,  // 15: pb.meal.getSetmealsByCategoryId:output_type -> pb.GetSetmealsByCategoryIdResp
	9,  // 16: pb.meal.getSetmealsById:output_type -> pb.GetSetmealsByIdResp
	12, // 17: pb.meal.getDishSimplesById:output_type -> pb.GetDishSimplesByIdResp
	16, // 18: pb.meal.getDishesByCategoryId:output_type -> pb.GetDishesByCategoryIdResp
	18, // 19: pb.meal.getDishesById:output_type -> pb.GetDishesByIdResp
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_meal_proto_init() }
func file_meal_proto_init() {
	if File_meal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meal_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Category); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meal_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetCategoryListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meal_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetCategoryListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meal_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Setmeal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meal_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetSetmealsByCategoryIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meal_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetSetmealsByCategoryIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meal_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SetmealDishes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meal_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*SetmealWithDishes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meal_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetSetmealsByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meal_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*GetSetmealsByIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meal_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*DishSimple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meal_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GetDishSimplesByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meal_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*GetDishSimplesByIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meal_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*Flavor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meal_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*Dish); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meal_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*GetDishesByCategoryIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meal_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*GetDishesByCategoryIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meal_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*GetDishesByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meal_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*GetDishesByIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meal_proto_goTypes,
		DependencyIndexes: file_meal_proto_depIdxs,
		MessageInfos:      file_meal_proto_msgTypes,
	}.Build()
	File_meal_proto = out.File
	file_meal_proto_rawDesc = nil
	file_meal_proto_goTypes = nil
	file_meal_proto_depIdxs = nil
}
