// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"hanye/service/cart/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/add",
					Handler: addCartHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/clean",
					Handler: cleanCartHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: getCartListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/sub",
					Handler: subCartHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/user/cart"),
	)
}
