// Code generated by goctl. DO NOT EDIT.
package types

type Category struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`
	Type       int64  `json:"type"`
	Sort       int64  `json:"sort"`
	Status     int64  `json:"status"`
	CreateUser int64  `json:"createUser"`
	UpdateUser int64  `json:"updateUser"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
}

type Default struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type Dish struct {
	Id         int64     `json:"id"`
	Name       string    `json:"name"`
	Pic        string    `json:"pic"`
	Detail     string    `json:"detail"`
	Price      float64   `json:"price"`
	Status     int64     `json:"status"`
	CategoryId int64     `json:"categoryId"`
	UpdateTime string    `json:"updateTime"`
	Flavors    []*Flavor `json:"flavors"`
}

type DishSimple struct {
	Name   string `json:"name"`
	Pic    string `json:"pic"`
	Detail string `json:"detail"`
	Copies int64  `json:"copies"`
}

type Flavor struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	List   string `json:"list"`
	DishId int64  `json:"dishId"`
}

type GetCategoryListReq struct {
}

type GetCategoryListResp struct {
	Default
	Categories []*Category `json:"data"`
}

type GetDishSimplesByIdReq struct {
	Id int64 `path:"id"`
}

type GetDishSimplesByIdResp struct {
	Default
	DishSimples []*DishSimple
}

type GetDishesByCategoryIdQueryReq struct {
	CategoryId int64 `json:"categoryId"`
}

type GetDishesByCategoryIdReq struct {
	CategoryId int64 `path:"categoryId"`
}

type GetDishesByCategoryIdResp struct {
	Default
	Dishes []*Dish `json:"data"`
}

type GetDishesByIdReq struct {
	DishId int64 `path:"dishId"`
}

type GetDishesByIdResp struct {
	Default
	Dishs struct {
		Id         int64     `json:"id"`
		Name       string    `json:"name"`
		Pic        string    `json:"pic"`
		Detail     string    `json:"detail"`
		Price      float64   `json:"price"`
		Status     int64     `json:"status"`
		CategoryId int64     `json:"categoryId"`
		UpdateTime string    `json:"updateTime"`
		Flavors    []*Flavor `json:"flavors"`
	} `json:"data"`
}

type GetSetmealsByCategoryIdQueryReq struct {
	CategoryId int64 `json:"categoryId"`
}

type GetSetmealsByCategoryIdReq struct {
	CategoryId int64 `path:"categoryId"`
}

type GetSetmealsByCategoryIdResp struct {
	Default
	Setmeals []*Setmeal `json:"data"`
}

type GetSetmealsByIdReq struct {
	Id int64 `path:"id"`
}

type GetSetmealsByIdResp struct {
	Default
	Setmeals *SetmealWithDishes `json:"data"`
}

type Setmeal struct {
	Id         int64   `json:"id"`
	Name       string  `json:"name"`
	Pic        string  `json:"pic"`
	Detail     string  `json:"detail"`
	Price      float64 `json:"price"`
	Status     int64   `json:"status"`
	CategoryId int64   `json:"categoryId"`
	CreateUser int64   `json:"createUser"`
	UpdateUser int64   `json:"updateUser"`
	CreateTime string  `json:"createTime"`
	UpdateTime string  `json:"updateTime"`
}

type SetmealDishes struct {
	Id        int64   `json:"id"`
	Name      string  `json:"name"`
	Price     float64 `json:"price"`
	Copies    int64   `json:"copies"`
	Pic       string  `json:"pic"`
	SetmealId int64   `json:"setmealId"`
	DishId    int64   `json:"dishId"`
}

type SetmealWithDishes struct {
	Id            int64            `json:"id"`
	Name          string           `json:"name"`
	Pic           string           `json:"pic"`
	Detail        string           `json:"detail"`
	Price         float64          `json:"price"`
	Status        int64            `json:"status"`
	CategoryId    int64            `json:"categoryId"`
	UpdateTime    string           `json:"updateTime"`
	SetmealDishes []*SetmealDishes `json:"setmealDishes"`
}
