// Code generated by goctl. DO NOT EDIT.
// Source: meal.proto

package server

import (
	"context"

	"hanye/service/meal/rpc/internal/logic"
	"hanye/service/meal/rpc/internal/svc"
	"hanye/service/meal/rpc/pb"
)

type MealServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMealServer
}

func NewMealServer(svcCtx *svc.ServiceContext) *MealServer {
	return &MealServer{
		svcCtx: svcCtx,
	}
}

func (s *MealServer) GetCategoryList(ctx context.Context, in *pb.GetCategoryListReq) (*pb.GetCategoryListResp, error) {
	l := logic.NewGetCategoryListLogic(ctx, s.svcCtx)
	return l.GetCategoryList(in)
}

func (s *MealServer) GetSetmealsByCategoryId(ctx context.Context, in *pb.GetSetmealsByCategoryIdReq) (*pb.GetSetmealsByCategoryIdResp, error) {
	l := logic.NewGetSetmealsByCategoryIdLogic(ctx, s.svcCtx)
	return l.GetSetmealsByCategoryId(in)
}

func (s *MealServer) GetSetmealsById(ctx context.Context, in *pb.GetSetmealsByIdReq) (*pb.GetSetmealsByIdResp, error) {
	l := logic.NewGetSetmealsByIdLogic(ctx, s.svcCtx)
	return l.GetSetmealsById(in)
}

func (s *MealServer) GetDishSimplesById(ctx context.Context, in *pb.GetDishSimplesByIdReq) (*pb.GetDishSimplesByIdResp, error) {
	l := logic.NewGetDishSimplesByIdLogic(ctx, s.svcCtx)
	return l.GetDishSimplesById(in)
}

func (s *MealServer) GetDishesByCategoryId(ctx context.Context, in *pb.GetDishesByCategoryIdReq) (*pb.GetDishesByCategoryIdResp, error) {
	l := logic.NewGetDishesByCategoryIdLogic(ctx, s.svcCtx)
	return l.GetDishesByCategoryId(in)
}

func (s *MealServer) GetDishesById(ctx context.Context, in *pb.GetDishesByIdReq) (*pb.GetDishesByIdResp, error) {
	l := logic.NewGetDishesByIdLogic(ctx, s.svcCtx)
	return l.GetDishesById(in)
}
