// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	category "hanye/service/meal/api/internal/handler/category"
	dish "hanye/service/meal/api/internal/handler/dish"
	setmeal "hanye/service/meal/api/internal/handler/setmeal"
	"hanye/service/meal/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: category.GetCategoryListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user/category"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/dish/:dishId",
				Handler: dish.GetDishesByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: dish.GetDishesByCategoryIdQueryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list/:categoryId",
				Handler: dish.GetDishesByCategoryIdHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user/dish"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: setmeal.GetSetmealsByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dish/:id",
				Handler: setmeal.GetDishSimplesByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: setmeal.GetSetmealsByCategoryIdQueryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list/:categoryId",
				Handler: setmeal.GetSetmealsByCategoryIdHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user/setmeal"),
	)
}
