// Code generated by goctl. DO NOT EDIT.
// Source: meal.proto

package meal

import (
	"context"

	"hanye/service/meal/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Category                    = pb.Category
	Dish                        = pb.Dish
	DishSimple                  = pb.DishSimple
	Flavor                      = pb.Flavor
	GetCategoryListReq          = pb.GetCategoryListReq
	GetCategoryListResp         = pb.GetCategoryListResp
	GetDishSimplesByIdReq       = pb.GetDishSimplesByIdReq
	GetDishSimplesByIdResp      = pb.GetDishSimplesByIdResp
	GetDishesByCategoryIdReq    = pb.GetDishesByCategoryIdReq
	GetDishesByCategoryIdResp   = pb.GetDishesByCategoryIdResp
	GetDishesByIdReq            = pb.GetDishesByIdReq
	GetDishesByIdResp           = pb.GetDishesByIdResp
	GetSetmealsByCategoryIdReq  = pb.GetSetmealsByCategoryIdReq
	GetSetmealsByCategoryIdResp = pb.GetSetmealsByCategoryIdResp
	GetSetmealsByIdReq          = pb.GetSetmealsByIdReq
	GetSetmealsByIdResp         = pb.GetSetmealsByIdResp
	Setmeal                     = pb.Setmeal
	SetmealDishes               = pb.SetmealDishes
	SetmealWithDishes           = pb.SetmealWithDishes

	Meal interface {
		GetCategoryList(ctx context.Context, in *GetCategoryListReq, opts ...grpc.CallOption) (*GetCategoryListResp, error)
		GetSetmealsByCategoryId(ctx context.Context, in *GetSetmealsByCategoryIdReq, opts ...grpc.CallOption) (*GetSetmealsByCategoryIdResp, error)
		GetSetmealsById(ctx context.Context, in *GetSetmealsByIdReq, opts ...grpc.CallOption) (*GetSetmealsByIdResp, error)
		GetDishSimplesById(ctx context.Context, in *GetDishSimplesByIdReq, opts ...grpc.CallOption) (*GetDishSimplesByIdResp, error)
		GetDishesByCategoryId(ctx context.Context, in *GetDishesByCategoryIdReq, opts ...grpc.CallOption) (*GetDishesByCategoryIdResp, error)
		GetDishesById(ctx context.Context, in *GetDishesByIdReq, opts ...grpc.CallOption) (*GetDishesByIdResp, error)
	}

	defaultMeal struct {
		cli zrpc.Client
	}
)

func NewMeal(cli zrpc.Client) Meal {
	return &defaultMeal{
		cli: cli,
	}
}

func (m *defaultMeal) GetCategoryList(ctx context.Context, in *GetCategoryListReq, opts ...grpc.CallOption) (*GetCategoryListResp, error) {
	client := pb.NewMealClient(m.cli.Conn())
	return client.GetCategoryList(ctx, in, opts...)
}

func (m *defaultMeal) GetSetmealsByCategoryId(ctx context.Context, in *GetSetmealsByCategoryIdReq, opts ...grpc.CallOption) (*GetSetmealsByCategoryIdResp, error) {
	client := pb.NewMealClient(m.cli.Conn())
	return client.GetSetmealsByCategoryId(ctx, in, opts...)
}

func (m *defaultMeal) GetSetmealsById(ctx context.Context, in *GetSetmealsByIdReq, opts ...grpc.CallOption) (*GetSetmealsByIdResp, error) {
	client := pb.NewMealClient(m.cli.Conn())
	return client.GetSetmealsById(ctx, in, opts...)
}

func (m *defaultMeal) GetDishSimplesById(ctx context.Context, in *GetDishSimplesByIdReq, opts ...grpc.CallOption) (*GetDishSimplesByIdResp, error) {
	client := pb.NewMealClient(m.cli.Conn())
	return client.GetDishSimplesById(ctx, in, opts...)
}

func (m *defaultMeal) GetDishesByCategoryId(ctx context.Context, in *GetDishesByCategoryIdReq, opts ...grpc.CallOption) (*GetDishesByCategoryIdResp, error) {
	client := pb.NewMealClient(m.cli.Conn())
	return client.GetDishesByCategoryId(ctx, in, opts...)
}

func (m *defaultMeal) GetDishesById(ctx context.Context, in *GetDishesByIdReq, opts ...grpc.CallOption) (*GetDishesByIdResp, error) {
	client := pb.NewMealClient(m.cli.Conn())
	return client.GetDishesById(ctx, in, opts...)
}
